version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing Terraform..."
      - curl -o terraform.zip https://releases.hashicorp.com/terraform/1.8.0/terraform_1.8.0_linux_amd64.zip
      - unzip -o terraform.zip -d /tmp
      - mv /tmp/terraform /usr/local/bin/terraform
      - terraform version

  pre_build:
    commands:
      - echo "Creating Lambda deployment packages..."
      - |
        for dir in lambdas/*; do
          if [ -d "$dir" ]; then
            name=$(basename "$dir")
            zip_path="$dir/$name.zip"
            echo "Creating zip for $dir → $zip_path"
            rm -f "$zip_path"
            if [ -f "$dir/requirements.txt" ]; then
              echo "Installing dependencies for $name"
              pip install -r "$dir/requirements.txt" -t "$dir"
            fi
            (cd "$dir" && zip -r "$name.zip" . -x "*.zip")
            echo "Created: $zip_path"
          fi
        done

  build:
    commands:
      - echo "Running Terraform deployment..."
      - cd terraform
      - terraform init
      - terraform apply -auto-approve
      - cd ..

  post_build:
    commands:
      - echo "Build finished at `date`"
      - echo "Listing created Lambda packages:"
      - find lambdas -name "*.zip" -exec ls -la {} \;

artifacts:
  files:
    - '**/*.zip'