version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
      nodejs: 16
    commands:
      - echo Installing Terraform...
      - curl -o terraform.zip https://releases.hashicorp.com/terraform/1.8.0/terraform_1.8.0_linux_amd64.zip
      - unzip -o terraform.zip -d /tmp
      - mv /tmp/terraform /usr/local/bin/terraform
      - terraform version


  pre_build:
    commands:
      - echo "Installing dependencies and preparing Lambda packages..."
      # Prepare Lambda zips in correct locations for Terraform
      - |
        for d in lambdas/*; do
          if [ -d "$d" ]; then
            echo "Processing $d"
            if [ -f "$d/requirements.txt" ]; then
              pip install -r "$d/requirements.txt" -t "$d"
            fi
            (cd "$d" && zip -r "$(basename $d).zip" .)
          fi
        done

  build:
    commands:
      - echo "Running Terraform..."
      - cd terraform
      - terraform init
      - terraform apply -auto-approve
      - cd ..

  post_build:
    commands:
      - echo "Build completed on `date`"

artifacts:
  files:
    - '**/*.zip'